### ISSUE TITLE
SecretsManagerRDSPostgreSQLRotationMultiUser doesn't support RDS Aurora Postgres

### ISSUE THREAD

**Issue by jurajseffer** [aws-samples/aws-secrets-manager-rotation-lambdas#105]
The lambda looks for `aws:rds:primarydbinstancearn` tag when looking up the master RDS username and password secret but this is not present on a secret created by an RDS cluster since that uses `aws:rds:primaryDBClusterArn` tag instead. This results in a "key host not found" error.

**Comment by jbct** [comment]
This was resolved with commit https://github.com/aws-samples/aws-secrets-manager-rotation-lambdas/commit/5c2d2f18be74dd542f3709a9badb794ce2f73ba4.
