### ISSUE TITLE
MySQL MultiUser Increase Username limit from 16 to 32

### ISSUE THREAD

**Issue by ivan-georgiev** [aws-samples/aws-secrets-manager-rotation-lambdas#110]
Function get_alt_username raises exception if username is above 16 chars, engine limit is 32 ( https://dev.mysql.com/doc/refman/5.7/en/user-names.html )

if len(new_username) > 16:
            raise ValueError("Unable to clone user, username length with _clone appended would exceed 16 characters")

**Comment by itsuki3** [comment]
Code branching based on version seems necessary.
For MySQL 5.6 (Aurora 1.x) ... 16 characters
For MySQL 5.7 (Aurora 2.x) ... 32 characters
For MySQL 8.0 (Aurora 3.x) ... 32 characters

**Comment by ivan-georgiev** [comment]
According to official version documentation Aurora 1.x is depreciated so may be branching is not needed. Source: https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.VersionPolicy.html

**Comment by adrianwright** [comment]
Given that Aurora 1.x is deprecated, would you receive a PR to check for 32 characters instead of 16, in all cases?

**Comment by adrianwright** [comment]
@crus-umich that should work. What if we optimized for the supported engines by making the default 32 instead of 16? Anyone still using old versions should be the exception.
