### ISSUE TITLE
secrets-manager automatic rotation for aws msk 

### ISSUE THREAD

**Issue by Giant-goose** [aws-samples/aws-secrets-manager-rotation-lambdas#111]
Hello, contributors to the aws-secrets-manager automatic rotation community, I would like to ask if there is currently an automatic rotation key lamda template for aws msk clusters. I have tried to write it myself, but it has never achieved the desired effect. Thank you

**Comment by simonmarty** [comment]
We do not currently support AWS MSK. Are you setting up SASL/SCRAM credentials following this [guide](https://docs.aws.amazon.com/msk/latest/developerguide/msk-password.html)?
