### ISSUE TITLE
Aurora-mysql rotation fix

### ISSUE THREAD

**Issue by GNUKalashnikov** [aws-samples/aws-secrets-manager-rotation-lambdas#118]
Within this file:
[SecretsManagerRDSMySQLRotationSingleUser](https://github.com/aws-samples/aws-secrets-manager-rotation-lambdas/tree/196703e8323533f98fdf6f9c7b5503e69a171b12/SecretsManagerRDSMySQLRotationSingleUser)
/lambda_function.py

I found a verfication check that only supports mysql.
From my testing, I found that changing from aurora-mysql to just mysql creates a functional password rotation for the aurora-mysql db

Found on line 421:

```python
    if 'engine' not in secret_dict or secret_dict['engine'] != 'mysql':
        raise KeyError("Database engine must be set to 'mysql' in order to use this rotation lambda")
    for field in required_fields:
        if field not in secret_dict:
            raise KeyError("%s key is missing from secret JSON" % field)
```

Propsed fix:
```python
    if 'engine' not in secret_dict or (secret_dict['engine'] != 'mysql' and secret_dict['engine'] != 'aurora-mysql'):
        raise KeyError("Database engine must be set to 'mysql' in order to use this rotation lambda")
    for field in required_fields:
        if field not in secret_dict:
            raise KeyError("%s key is missing from secret JSON" % field)
```

This will allow for the verfication to pass aurora-mysql

**Comment by crus-umich** [comment]
Thank you for reaching out, we added the aurora engine types for the MySQL single user rotation lambda in the most recent PR.
