### ISSUE TITLE
cx_Oracle has a major new release under a new name python-oracledb

### ISSUE THREAD

**Issue by Balvinder-1995** [aws-samples/aws-secrets-manager-rotation-lambdas#125]
After upgrading the lambda runtime from python 3.8 to 3.11, It has been found that cx_Oracle is not supported and should be replaced with python-oracledb. However, cx_Oracle is working till python 3.10 version.

[ERROR] Runtime.ImportModuleError: Unable to import module 'lambda_function': No module named 'cx_Oracle' Traceback (most recent call last):
--

https://cx-oracle.readthedocs.io/en/latest/index.html

**Comment by wlewis4321** [comment]
Completed in #134
