### ISSUE TITLE
MySQL and PostgreSQL support for aurora is inconsistent.

### ISSUE THREAD

**Issue by neilchandler** [aws-samples/aws-secrets-manager-rotation-lambdas#129]
Thanks to Pull Request #117 there is support for aurora engine types in `SecretsManagerRDSMySQLRotationMultiUser` [here](https://github.com/aws-samples/aws-secrets-manager-rotation-lambdas/blob/master/SecretsManagerRDSMySQLRotationMultiUser/lambda_function.py#L481-L482) and `SecretsManagerRDSPostgreSQLRotationMultiUser` [here](https://github.com/aws-samples/aws-secrets-manager-rotation-lambdas/blob/master/SecretsManagerRDSPostgreSQLRotationMultiUser/lambda_function.py#L473-L474)

But the aurora engine types are not supported by `SecretsManagerRDSMySQLRotationSingleUser` [here](https://github.com/aws-samples/aws-secrets-manager-rotation-lambdas/blob/master/SecretsManagerRDSMySQLRotationSingleUser/lambda_function.py#L421) or `SecretsManagerRDSPostgreSQLRotationSingleUser` [here](https://github.com/aws-samples/aws-secrets-manager-rotation-lambdas/blob/master/SecretsManagerRDSPostgreSQLRotationSingleUser/lambda_function.py#L432)

**Comment by crus-umich** [comment]
Thank you for reaching out, we added the aurora engine types for consistency in the most recent PR.

**Comment by neilchandler** [comment]
Thank you for the quick inclusion of this change.
I've close my related PR#130 to keep things clean.
