### ISSUE TITLE
Secrets rotation fails for Oracle RDS with SSL or NNE 

### ISSUE THREAD

**Issue by smislam** [aws-samples/aws-secrets-manager-rotation-lambdas#132]
Based on the documentation, [Oracle RDS Secrets rotation for SSL](https://docs.aws.amazon.com/secretsmanager/latest/userguide/rotate-secrets_turn-on-for-db.html#rotate-secrets_turn-on-for-db_step2) is not supported.

I am testing with Oracle NNE (with endpoints for both Secrets Manager and RDS) and getting the following error.  
```
[ERROR] ValueError: Unable to log into database with previous, current, or pending secret of secret arn arn:aws:secretsmanager:REGION:ACCOUNT:secret:MYSECRET
```

This would be for both Single and Multi user flows.  Is there any plans to support RDS Oracle credential rotation with SSL or NNE in near future?  If not, do you have any recommendations?

**Comment by holomekc** [comment]
We have the same issue. After downloading the lambda code and adding some logging I can see:

Connection to db failed: SCRAM authentication requires libpq version 10 or above

**Comment by mim-Armand** [comment]
Bumping this up!
AWS, any feedback or information we can get about this issue?

**Comment by smislam** [comment]
@jbct, I wanted to give you more information on this.  Please DM me if you need additional info.  The Lambda works when you have the following parameters unset or set to 'true' and 'ACCEPTED' respectfully in RDS Options group.  However, it is not recommended for security reasons.

``` typescript
'SQLNET.ALLOW_WEAK_CRYPTO_CLIENTS': 'FALSE',
'SQLNET.ENCRYPTION_CLIENT': 'REQUIRED',
```
