### ISSUE TITLE
SqlServer rotation not respecting EXCLUDE_CHARACTERS

### ISSUE THREAD

**Issue by BlueMaegi** [aws-samples/aws-secrets-manager-rotation-lambdas#133]
I was sent here from AWS technical support since apparently this issue is out of their "scope". Apologies if this is not something actually wrong with the lambda code.

Our autogenerated lambda function that handles our RDS password rotation for MS SqlServer has stopped factoring in the EXCLUDE_CHARACTERS environment variable. 

We have it set to exclude the following characters: /\@"'[]{}%#* 
<img width="456" alt="Screen Shot 2024-02-22 at 10 43 50 AM" src="https://github.com/aws-samples/aws-secrets-manager-rotation-lambdas/assets/20377904/bcf40082-cbff-4b71-97dc-e5f4637e3d09">

Yet it is consistently generating passwords with those characters included. Like this example (not currently in use):
<img width="438" alt="Screen Shot 2024-02-22 at 10 45 30 AM" src="https://github.com/aws-samples/aws-secrets-manager-rotation-lambdas/assets/20377904/8ed3079f-df97-42cb-b20b-35e2c32bd810">

From the CloudWatch logs it looks like the lambda stopped running entirely sometime in late November 2023, so I'm a bit confused about where the new rotated passwords are even coming from. There are no new rotation lambdas anywhere on our account.

**Comment by jbct** [comment]
Hi @BlueMaegi - when was this lambda deployed that began causing the issue? I just tried reproducing it myself and it's excluding the characters in a large character length password. Wondering if something else changed the password without the exclusion given this one hasn't ran since Nov 2023.

**Comment by BlueMaegi** [comment]
The lambda was created in May 2023 and has not been touched since. It was autogenerated the first time we spun up an RDS instance with SecretsManager rotation enabled. We've never "deployed" it from our own code.

My thought was to delete it, and tear down all the associated RDS instances to start from scratch. But we lack knowledge on what drives/creates the rotation lambdas to be sure that such a process would even work.

**Comment by BlueMaegi** [comment]
On the rotation tab, it says the following:
"Amazon RDS (rds) manages rotation for this secret, so you don't need to choose a Lambda rotation function."

Regardless, I've attached the file from the autogenerated function, which is probably not running anymore.

[lambda_function.txt](https://github.com/aws-samples/aws-secrets-manager-rotation-lambdas/files/14389070/lambda_function.txt)

**Comment by jirkafajfr** [comment]
There are actually two distinct concepts:
- [Managed rotation](https://docs.aws.amazon.com/secretsmanager/latest/userguide/rotate-secrets_managed.html)
- [Rotation lambdas](https://docs.aws.amazon.com/secretsmanager/latest/userguide/rotating-secrets.html)

In your case the secret is rotated by RDS (managed rotation), but you're trying to change parameters of rotation lambda that is not being used (at least for secret you reference here).

**Comment by jirkafajfr** [comment]
@BlueMaegi the managed rotations doesn't allow user to specify criteria for a random password generation. If you really need control over the characters used in password you'll need to switch your secret to rotation lambdas away from managed rotation.

I'll close the ticket now, but feel free to re-open.
