### ISSUE TITLE
Lambda for sql database rotation does not work as expected

### ISSUE THREAD

**Issue by mobious999** [aws-samples/aws-secrets-manager-rotation-lambdas#149]
Hi,

Pymssql has been deprecated and no longer functions when attempting to rotate passwords.

#https://docs.aws.amazon.com/secretsmanager/latest/userguide/rotating-secrets-required-permissions-function.html

The Microsoft stance is that you should be using pyodbc.
https://learn.microsoft.com/en-us/sql/connect/python/pyodbc/python-sql-driver-pyodbc?view=sql-server-ver16

Also there is no guide on how to get the lambda to rotation to work with ssl connections to the database.

**Comment by jirkafajfr** [comment]
Hi Mark, 

would you mind sharing more information with us? We're interested about your:
- Python version
- MSSQL version
- Error message you see in your rotation lambda logs

We are running integration tests against rotation functions, and don't observe anything out of ordinary. Microsoft still advertises [pymssql](https://learn.microsoft.com/en-us/sql/connect/python/pymssql/python-sql-driver-pymssql?view=sql-server-ver16) as supported driver.

**Comment by mobious999** [comment]
Hi @jirkafajfr,

They python version is 3.11, and you can build the layer to whatever version you need.

The sql server version is 17 I believe, and pymssql failed with the ssl connections originally and it's undocumented.

I stopped using the pymssql lambda function after the second set of failures because of the ssl issues (it won't connect to the database, and there are no options that require ssl set). 

As you can see - https://github.com/pymssql/pymssql/issues?page=1&q=is%3Aissue+is%3Aopen the project has 150 open issues and it is not actively being worked on.

As compared to pyodbc - https://github.com/mkleehammer/pyodbc/issues 35 known issues and is actively being worked on.

I'm glad you can get the pymssql working but I was forced to give up due to time constraints.

**Comment by jirkafajfr** [comment]
Hi Mark,

the latest sql server is version 16 ([reference](https://learn.microsoft.com/en-us/troubleshoot/sql/releases/download-and-install-latest-updates)). When you say 17 do you mean 2017? I can verify with our integration tests that the library is really not a problem - but I need to know the exact versions - right now we don't see any failures in our coverage.

I agree that pyodbc is newer and more maintained version. But as pointed out in previous post pymssql is still advertised as [valid driver on the Microsoft site](https://learn.microsoft.com/en-us/sql/connect/python/pymssql/python-sql-driver-pymssql?view=sql-server-ver16). We have no plans to migrate away from pymsql unless Microsoft declares it as not recommended solution or if there is a compatibility problem. 

Please feel free to share exact SSL problems you're experiencing. But unless we can reproduce on our side, we are not willing to migrate away from current driver.

I also wanted to let you know that these lambdas are reference implementation for customers that want to customize the code. Using one of the following two deployment options is typically much easier and you don't have to worry about exact python / driver versions:

### Service Application Repository
- [SecretsManagerRDSSQLServerRotationSingleUser](https://us-west-2.console.aws.amazon.com/lambda/home?region=us-west-2#/create/app?applicationId=arn:aws:serverlessrepo:us-east-1:297356227824:applications/SecretsManagerRDSSQLServerRotationMultiUser)
- [SecretsManagerRDSSQLServerRotationMultiUser](https://us-west-2.console.aws.amazon.com/lambda/home?region=us-west-2#/create/app?applicationId=arn:aws:serverlessrepo:us-east-1:297356227824:applications/SecretsManagerRDSSQLServerRotationMultiUser)

### CloudFormation - Transform
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-aws-secretsmanager.html
