### ISSUE TITLE
Mismatching tokens

### ISSUE THREAD

**Issue by sb-ovo** [aws-samples/aws-secrets-manager-rotation-lambdas#16]
Hi,

I'm trying to setup secretsmanager rotation and found these lambda function examples here... but can't get these to work.
It seems like the tokens received by Lambda (event) don't match the tokens/VersionStages  fetched when calling seceretsmanager API (describe_secret), so the function fails raising an exception. 

Please see the Lambda output below:
```
START RequestId: 869a3608-f930-43dd-9337-b71edc57f134 Version: $LATEST

EVENT_DATA: {'ClientRequestToken': 'AF585B8F-AA06-4EAB-8827-EFF43E6FD896', 'SecretId': 'arn:aws:secretsmanager:eu-west-1:passwd-WqYjGj', 'Step': 'createSecret'}

DESC_SECRET {'ARN': 'arn:aws:secretsmanager:eu-west-1:passwd-WqYjGj', 'Name': 'passwd', 'KmsKeyId': '41b10ffe-b86d-412f-8bb5-d63ba990e585', 'RotationEnabled': True, 'RotationLambdaARN': 'arn:aws:lambda:eu-west-1:XXX:function:rotate-secrets', 'RotationRules': {'AutomaticallyAfterDays': 90}, 'LastChangedDate': datetime.datetime(2019, 8, 5, 16, 18, 40, 344000, tzinfo=tzlocal()), 'Tags': [{'Key': 'Environment', 'Value': 'uat'}, {'Key': 'Owner', 'Value': 'terraformer'}, {'Key': 'Terraform', 'Value': 'true'}], 'VersionIdsToStages': {'AF585B8F-AA06-4EAB-8827-EFF43E6FD896': ['AWSPENDING']}, 'ResponseMetadata': {'RequestId': '75613522-63e9-42c3-999c-ba1d728f08e8', 'HTTPStatusCode': 200, 'HTTPHeaders': {'date': 'Mon, 05 Aug 2019 16:18:41 GMT', 'content-type': 'application/x-amz-json-1.1', 'content-length': '583', 'connection': 'keep-alive', 'x-amzn-requestid': '75613522-63e9-42c3-999c-ba1d728f08e8'}, 'RetryAttempts': 0}}

[ERROR] ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the GetSecretValue operation: Secrets Manager can’t find the specified secret value for staging label: AWSCURRENT

Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 61, in lambda_handler
    create_secret(service_client, arn, token)
  File "/var/task/lambda_function.py", line 88, in create_secret
    service_client.get_secret_value(SecretId=arn, VersionStage="AWSCURRENT")
  File "/var/runtime/botocore/client.py", line 320, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/runtime/botocore/client.py", line 623, in _make_api_call
    raise error_class(parsed_response, operation_name)

END RequestId: 869a3608-f930-43dd-9337-b71edc57f134

REPORT RequestId: 869a3608-f930-43dd-9337-b71edc57f134	Duration: 1039.40 ms	Billed Duration: 1100 ms Memory Size: 128 MB	Max Memory Used: 71 MB	
 ```

Can you please advise on how to solve that issue ?

**Comment by jchannon** [comment]
Just had a the same error message in a .net app. No idea what it means

**Comment by ThinTim** [comment]
If it helps at all, I get that error when there's no version with the label `AWSCURRENT` for the given secret:

```
aws secretsmanager get-secret-value --secret-id my_secret --version-stage RANDOM 

An error occurred (ResourceNotFoundException) when calling the GetSecretValue operation: Secrets Manager can’t find the specified secret value for staging label: RANDOM
```

If that's the case, a possible resolution would be to just assign the `AWSCURRENT` label to whatever version of your secret you're currently using:

```
aws secretsmanager update-secret-version-stage --secret-id my_secret --version-stage AWSCURRENT  --move-to-version-id whatever_current_version_id_is
```

If it's already assigned to something else, I believe this call would raise an error asking for explicit version IDs for both sides of the transaction.

**Comment by sb-ovo** [comment]
Thx @ThinTim , but in my case it's not going to help. 

I'm creating secrets using Terraform, and since I set these to rotate automatically, AWS starts a rotation process right away after creation. 

That means I have no control over the versions/stages, AWS is triggering all that and calling my Lambda function automatically. (probably a step function behind the scene)
And that's the issue: when calling Lambda, AWS sends me a token that is supposed to match a stage... but doesn't match anything when I fetch data from the secretsmanager API.

**Comment by rstevens011** [comment]
Terraform may be rotating the secret before putting a initial secret value.  Terraform makes a distinction between a secret and a secret version.  It'd probably be helpful to have a look at your CloudTrail logs to see the individual API calls and the order they are called in.

**Comment by ayshamdmgit** [comment]
@sb-ovo  Were you able to resolve this?

**Comment by joebaro** [comment]
If you are still experiencing this issue please open a support case with AWS.
