### ISSUE TITLE
Clarification the Python Runtime version these lambdas should use

### ISSUE THREAD

**Issue by sheridansmall** [aws-samples/aws-secrets-manager-rotation-lambdas#18]
Could you please clarify the Python Runtime version these lambdas should use. I notice that SecretsManagerRDSPostgreSQLRotationSingleUser — version 1.0.117 is used in the AWS Serverless Application Repository. The template in the repository contains Runtime: python2.7. Can SecretsManagerRDSPostgreSQLRotationSingleUser be safely used with Runtime: python3.7?

**Comment by rstevens011** [comment]
The SAR apps vended by Secrets Manager use the 2.7 runtime as of today.  The Lambda EOL date for 2.7 has not been announced on https://docs.aws.amazon.com/lambda/latest/dg/runtime-support-policy.html and is therefore supported for the time being.
