### ISSUE TITLE
Creation of AWS-secret-manager-rotation-lambda in .net

### ISSUE THREAD

**Issue by 1ds14te050manoj** [aws-samples/aws-secrets-manager-rotation-lambdas#22]
Hi everyone,
 Can anyone please point me to a document or link where i can find a generic template or code to build solution to rotate secret from lambda function in .net language. i have seen the available one is in python but i am not sure how to begin in .net. 
Please provide me your guidance as i am new to both AWS lambdas and secret manager.

Thank you.

**Comment by lasred** [comment]
There are not any generic templates or code to rotate secrets in the .net language. You could follow the general guidelines and overview of the rotation lambda here - https://docs.aws.amazon.com/secretsmanager/latest/userguide/rotating-secrets-lambda-function-overview.html and follow the existing Python template to write the .NET version. 

Is there fundamental something about the existing python lambda rotation lambdas that does not fit your usecase?  I prefer for you to write a customized python rotation lambda based off the python template and not start from scratch in dotnet.

**Comment by 1ds14te050manoj** [comment]
Thank you @lasred i will try what you said and will get back.

**Comment by 1ds14te050manoj** [comment]
I am using the below snippet code which consist DescribeSecret method but i am facing an error due to protection level. I am using DescribeSecret to get all the secret values excluding the encrypted one. I have defined the configuration but i am not putting it below in the code snippet.
code:
var client = new AmazonSecretsManagerClient(smConfig);

            //Make sure the version is staged correctly
           
            
            var response = client.DescribeSecret(new DescribeSecretRequest
            {
                SecretId = secretName
            });

            string arn = response.ARN;
            string description = response.Description;
            string kmsKeyId = response.KmsKeyId;
            DateTime lastAccessedDate = response.LastAccessedDate;
            DateTime lastChangedDate = response.LastChangedDate;
            DateTime lastRotatedDate = response.LastRotatedDate;
            string name = response.Name;
            bool rotationEnabled = response.RotationEnabled;
            string rotationLambdaARN = response.RotationLambdaARN;
            RotationRulesType rotationRules = response.RotationRules;

Error I am facing is in this line  var response = client.DescribeSecret(new DescribeSecretRequest.
Error:
'AmazonSecretsManagerClient.DescribeSecret(DescribeSecretRequest)' is inaccessible due to its protection level.

**Comment by lasred** [comment]
I was able to reproduce this error. 

Can you try calling DescribeSecretAsync instead - https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/SecretsManager/MSecretsManagerDescribeSecretAsyncDescribeSecretRequestCancellationToken.html ? 

DescribeSecret should work as well according to our documentation - https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/SecretsManager/TSecretsManagerClient.html

And in the dotnet aws sdk, both methods are defined as public - https://github.com/aws/aws-sdk-net/blob/189abfb1d51c5300e68c741c536f4144d5f2c4fd/sdk/src/Services/SecretsManager/Generated/_bcl45/AmazonSecretsManagerClient.cs


Let me investigate this further as well(why DescribeSecret is inaccessibel). Let me know if DescribeSecretAsync unblocks you/works on your end.

**Comment by 1ds14te050manoj** [comment]
![image](https://user-images.githubusercontent.com/27077036/67652580-8e8e0600-f96b-11e9-8eff-dab181f6646b.png)
I am using DescribeSecretAsync but as you see in the image it does not have the below variables as response which i require.

**Comment by lasred** [comment]
Is it just an issue with your IDE-Visual Studio I'am guessing? Can you build this project?

ARN should be a property of DescribeSecretResponse - See https://github.com/aws/aws-sdk-net/blob/9d60d369808c68967ea42e0119c0815f6654142e/sdk/src/Services/SecretsManager/Generated/Model/DescribeSecretResponse.cs

**Comment by lasred** [comment]
For your initial question(building the rotation lambdas in dotnet), have a look at this as well - https://github.com/aws-samples/aws-secrets-manager-rotation-lambdas/pull/19
