### ISSUE TITLE
Python 2.7 EOL January 1, 2020

### ISSUE THREAD

**Issue by ryancausey** [aws-samples/aws-secrets-manager-rotation-lambdas#24]
It looks like Python 2.7 is going to stop being supported as of January 1, 2020 based on the information found here:
https://devguide.python.org/#status-of-python-branches

I'm assuming that a lambda runtime environment deprecation will follow soon after.

Last I remember trying to run the RDS single user rotation for PostgreSQL in a Python 3 lambda runtime, it was not compatible. Is there a plan to upgrade these to be Python 3 compatible?

**Comment by brucedvgw** [comment]
+ 1 on this please.

**Comment by ScriptAutomate** [comment]
+1

I have a feeling many of the AWS sample repos will need an audit, and porting over to Python 3.

Just so people see this, and are aware, AWS says this in regard to AWS Lambda Python 2.7 runtime support in relation to the 2.7 EOL:

> _To allow you additional time to prepare, **AWS Lambda will continue to provide critical security patches for the Python 2.7 runtime until at least December 31, 2020.** Lambda’s scope of support includes the Python interpreter and standard library, but does not extend to third-party packages._

Source, with resource links related to porting to Python 3: https://aws.amazon.com/blogs/compute/continued-support-for-python-2-7-on-aws-lambda/

**Comment by mlehner616** [comment]
Is there any update or movement on this? We're only a couple months away from December 31, 2020 and I'd like to stay in-line with the sample lambdas while also not having our rotations stop working. These lambdas are part of Terraform instrumentation and deploying these via the UI for dozens of databases really isn't practical.

**Comment by willtong1234** [comment]
All of the Secrets Manager rotation lambdas have been migrated to the Python 3.7 runtime. Resolving this issue.
