### ISSUE TITLE
Rotation lambda function in JS: facing error- Invalid or unexpected token

### ISSUE THREAD

**Issue by 1ds14te050manoj** [aws-samples/aws-secrets-manager-rotation-lambdas#25]
Hi all,
   I am using the below code in node JS to rotate the secret but i am facing an error. I am mentioning the code and the error below.I am not using client request token assuming it's an optional parameter. Please let me know where i am going wrong.
 
**Code:**
	
 // Ensure you have installed these two packages
const AWS = require('aws-sdk');

const ServiceURL = "https://vpce-0ee-s82syo9o.secretsmanager.us-east-1.vpce.amazonaws.com/";
const endpoint = ServiceURL;
const region = "us-east-1";
const secretName = "1033-Rotation-Lambda";
const rotationInterval = 30; 
const rotationLambdaARN = "arn:aws:lambda:us-east-36390381:function:1033_PasswordRotation";

const secretsManager = new AWS.SecretsManager({
  endpoint: endpoint,
  region: region,
});

const params = {
  SecretId: secretName,
  RotationLamdaARN: rotationLambdaARN,
  RotationRules: {
    AutomaticallyAfterDays: rotationInterval,
  },
};

exports.handler = async (event, context) => {
  try {
    const response = await secretsManager.rotateSecret(params).promise();
    console.log(`${secretName} secret rotation complete`);
    console.log(response);
  } catch (error) {
    console.error(`An error occurred while attempting to rotate ${secretName} secret`);
    console.log(error);
  }
};

// SAMPLE ENVIRONMENT/CONFIG FILES- Use what fits your current app setup

/**
 * Sample config folder
 * this assumes you're using ES5
 */
// config/default.js
// REPLACE THE FOLLOWING WITH THE CORRECT VALUES!
module.exports = {
  AWS: {
    endpoint: 'https://vpce-0ee-s82syo9o.secretsmanager.us-east-1.vpce.amazonaws.com/',
    region: 'us-east-1',
    secretName: '1033-Rotation-Lambda',
    clientToken: 'token',
    rotation: {
      interval: 30,
      lambdaARN: 'arn:aws:lambda:us-east-36390381:function:1033_PasswordRotation'
    }
  },
};

/**
 * If you're reading values from the .env file
 */
const {
  AWS_ENDPOINT,
  AWS_REGION,
  AWS_SECRET_NAME,
  AWS_CLIENT_TOKEN,
  AWS_SECRET_ROTATION_INTERVAL,
} = process.env;

**Error:**

Response:
{
  "errorType": "Runtime.UserCodeSyntaxError",
  "errorMessage": "SyntaxError: Invalid or unexpected token",
  "trace": [
    "Runtime.UserCodeSyntaxError: SyntaxError: Invalid or unexpected token",
    "    at _loadUserApp (/var/runtime/UserFunction.js:98:13)",
    "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
    "    at Object.<anonymous> (/var/runtime/index.js:45:30)",
    "    at Module._compile (internal/modules/cjs/loader.js:778:30)",
    "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)",
    "    at Module.load (internal/modules/cjs/loader.js:653:32)",
    "    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:585:3)",
    "    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)",
    "    at startup (internal/bootstrap/node.js:283:19)"
  ]
}

Request ID:
"6705fb8f-b909-4381-b8c3-cfbffa6f7d18"

Function Logs:
START RequestId: 6705fb8f-b909-4381-b8c3-cfbffa6f7d18 Version: $LATEST
2019-11-11T10:17:04.575Z	undefined	ERROR	Uncaught Exception	{"errorType":"Runtime.UserCodeSyntaxError","errorMessage":"SyntaxError: Invalid or unexpected token","stack":["Runtime.UserCodeSyntaxError: SyntaxError: Invalid or unexpected token","    at _loadUserApp (/var/runtime/UserFunction.js:98:13)","    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)","    at Object.<anonymous> (/var/runtime/index.js:45:30)","    at Module._compile (internal/modules/cjs/loader.js:778:30)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)","    at Module.load (internal/modules/cjs/loader.js:653:32)","    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)","    at Function.Module._load (internal/modules/cjs/loader.js:585:3)","    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)","    at startup (internal/bootstrap/node.js:283:19)"]}
END RequestId: 6705fb8f-b909-4381-b8c3-cfbffa6f7d18
REPORT RequestId: 6705fb8f-b909-4381-b8c3-cfbffa6f7d18	Duration: 1903.34 ms	Billed Duration: 2000 ms	Memory Size: 128 MB	Max Memory Used: 24 MB	
Unknown application error occurred
Runtime.UserCodeSyntaxError

**Comment by joebaro** [comment]
If you are still experiencing this error, please open a support case with AWS.
