### ISSUE TITLE
get_secret_value() parameters

### ISSUE THREAD

**Issue by porjo** [aws-samples/aws-secrets-manager-rotation-lambdas#28]
The usage of `get_secret_value()` [here](https://github.com/aws-samples/aws-secrets-manager-rotation-lambdas/blob/master/SecretsManagerRDSMySQLRotationSingleUser/lambda_function.py#L306) appears wrong. The [API docs](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/secretsmanager.html#SecretsManager.Client.get_secret_value) says that either `VersionId` or `VersionStage` should be specified, but not both.

**Comment by joebaro** [comment]
The documentation does not mean that you can not use both, only that you do not need to use both. When both parameters are specified, the API checks that they are in agreement. This is an additional safety check to prevent rotation when someone is manually updating the secret.
