### ISSUE TITLE
Code for 2-user secret rotation for Redshift does not match Boto3 documentation.

### ISSUE THREAD

**Issue by nielsen-at-cgt** [aws-samples/aws-secrets-manager-rotation-lambdas#29]
Line 357 of SecretsManagerRedshiftRotationMultiUser/lambda_function.py says:

```secret = service_client.get_secret_value(SecretId=arn, VersionId=token, VersionStage=stage)```

Note that both `VersionId` and `VersionStage` are specified. 

Boto3 documentation for `get_secret_value()` says you don't specify both.  

What are the semantics when you _do_ specify both?

Why does the provided code disregard the documentation?

> VersionId (string) --
Specifies the unique identifier of the version of the secret that you want to retrieve. **If you specify this parameter then don't specify VersionStage** . If you don't specify either a VersionStage or VersionId then the default is to perform the operation on the version with the VersionStage value of AWSCURRENT .
>
>This value is typically a UUID-type value with 32 hexadecimal digits.
>
>VersionStage (string) --
Specifies the secret version that you want to retrieve by the staging label attached to the version.
>
>Staging labels are used to keep track of different versions during the rotation process. **If you use this parameter then don't specify VersionId** . If you don't specify either a VersionStage or VersionId , then the default is to perform the operation on the version with the VersionStage value of AWSCURRENT .

**Comment by joebaro** [comment]
The documentation does not mean that you can not use both, only that you do not need to use both. When both parameters are specified, the API checks that they are in agreement. This is an additional safety check to prevent rotation when someone is manually updating the secret.
