### ISSUE TITLE
SQL Injection Vulnerability

### ISSUE THREAD

**Issue by apnsngr** [aws-samples/aws-secrets-manager-rotation-lambdas#45]
Improper SQL query building is present in the several of the password rotation functions. For example, [SecretsManagerRDSPostgreSQLRotationSingleUser](https://github.com/aws-samples/aws-secrets-manager-rotation-lambdas/blob/master/SecretsManagerRDSPostgreSQLRotationSingleUser/lambda_function.py#L174-L175):

```python
alter_role = "ALTER USER \"%s\"" % pending_dict['username']
cur.execute(alter_role + " WITH PASSWORD %s", (pending_dict['password'],))
```

`pending_dict['username']` should be escaped as an identifier, unfortunately PyGreSQL does not expose this function easily.

**Comment by joebaro** [comment]
Thank you for opening this issue - we are looking into it.

**Comment by kboxeth** [comment]
PR #59 updates the rotation lambdas to escape usernames, which addresses this issue. Resolving.
