### ISSUE TITLE
An error occurred (AccessDeniedException) when calling the GetSecretValue operation: Access to KMS is not allowed

### ISSUE THREAD

**Issue by mealbarracin10** [aws-samples/aws-secrets-manager-rotation-lambdas#53]
Hey, I'm trying to execute the lambda [function](https://github.com/aws-samples/aws-secrets-manager-rotation-lambdas/blob/master/SecretsManagerRDSPostgreSQLRotationMultiUser/lambda_function.py), but it shows me an error. 

ClientError: An error occurred (AccessDeniedException) when calling the GetSecretValue operation: Access to KMS is not allowed

FIle "/../lambda_function.py"
secret = service_client.get_secret_value(SecretId=arn, VersionStage=stage)

https://github.com/aws-samples/aws-secrets-manager-rotation-lambdas/blob/master/SecretsManagerRDSPostgreSQLRotationMultiUser/lambda_function.py#L337

I already applied for these permissions 

       "kms:Encrypt",
       "kms:Decrypt",
       "kms:ReEncrypt*",
        "kms:GenerateDataKey"

thanks in advance

**Comment by sunnynazar** [comment]
Even i am getting the same exception but for mysql. Even though all permissions are there.

[ERROR] ClientError: An error occurred (AccessDeniedException) when calling the GetSecretValue operation: Access to KMS is not allowed
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 72, in lambda_handler
    create_secret(service_client, arn, token)
  File "/var/task/lambda_function.py", line 108, in create_secret
    current_dict = get_secret_dict(service_client, arn, "AWSCURRENT")
  File "/var/task/lambda_function.py", line 310, in get_secret_dict
    secret = service_client.get_secret_value(SecretId=arn, VersionStage=stage)
  File "/var/runtime/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/runtime/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)

**Comment by chrisoverzero** [comment]
This error usually occurs because the KMS key attached to a secret has changed. Changing the key associated with a secret via the AWS CLI does not re-encrypt the secret using the new key. (But doing so via the console does.) Please try following the steps from [AWS Premium Support][aps] to see if that resolves the issue.

[aps]: https://aws.amazon.com/premiumsupport/knowledge-center/secrets-manager-cross-account-key/

**Comment by joebaro** [comment]
If, after following @chrisoverzero advice, you are still experiencing this issue please open a support case with AWS.
