### ISSUE TITLE
Rotate Secret With Reader Endpoint

### ISSUE THREAD

**Issue by stewartcampbell** [aws-samples/aws-secrets-manager-rotation-lambdas#60]
Hello.

We are planning to have Postgres roles that have the reader endpoint in the secret host attribute to enforce use of the Aurora reader endpoint without the application having to worry about changing endpoint URL's. Am I right in thinking that rotation will fail due to the reader endpoint being passed to the rotation Lambda?

If so, what is the solution? Customize the Lambda? Change our approach?

Thanks.

**Comment by joebaro** [comment]
As shown in the [rotation docs](https://docs.aws.amazon.com/secretsmanager/latest/userguide/reference_available-rotation-templates.html) the rotation lambda will be looking for the secret to be filled in with a JSON structure like (assuming single user rotation):

    {
      "engine": "postgres",
      "host": "<required: instance host name/resolvable DNS name>",
      "username": "<required: username>",
      "password": "<required: password>",
      "dbname": "<optional: database name. If not specified, defaults to 'postgres'>",
      "port": "<optional: TCP port number. If not specified, defaults to 5432>"
    }

The "host" entry must be a writable endpoint so the rotation Lambda can change the password. However, other entries can be added to the JSON structure and will be ignored by the rotation Lambda so you can add the read only replica(s) or CNAME using some attribute other than the ones already in use.
