### ISSUE TITLE
Syntax error in module 'lambda_function

### ISSUE THREAD

**Issue by hemantproTR** [aws-samples/aws-secrets-manager-rotation-lambdas#69]
{
  "errorMessage": "Syntax error in module 'lambda_function': invalid syntax (__init__.py, line 3)",
  "errorType": "Runtime.UserCodeSyntaxError",
  "stackTrace": [
    "  File \"/var/task/pg/__init__.py\" Line 3\n        async,\n"
  ]
}

**Comment by joebaro** [comment]
I am sorry, there is not enough information here to tell what is going wrong. If you are still experiencing this issue please open a support case with AWS.
