### ISSUE TITLE
Clarify expected behavior if test stage fails

### ISSUE THREAD

**Issue by mdavis-xyz** [aws-samples/aws-secrets-manager-rotation-lambdas#71]
Please modify the docstring comment for the [`test_secret`](https://github.com/aws-samples/aws-secrets-manager-rotation-lambdas/blob/f7663e746949ef78b5c8c0beed9c25d2e2124367/SecretsManagerRotationTemplate/lambda_function.py#L125) function.

What is my code supposed to do if the test fails? Do I return False, or throw an exception? If an exception, which exception?

**Comment by whygoyal** [comment]
Thank you for your feedback. We have noted this as a feature request.

**Comment by jbct** [comment]
Hi mdavis. We expect that there are exceptions raised for any errors encountered. Which particular exceptions are irrelevant to Secrets Manager - we're tracking that the testSecret step failed, the rest would show up in your CloudWatch logs for debugging.

**Comment by mdavis-xyz** [comment]
Ok, thanks for the explanation.

As someone in the target audience, that wasn't what I expected. So I've written a PR to clarify that.
