### ISSUE TITLE
Help with this error - Runtime.UserCodeSyntaxError: Syntax error in module 'lambda_function': invalid syntax 

### ISSUE THREAD

**Issue by vitarkah** [aws-samples/aws-secrets-manager-rotation-lambdas#74]
So did the following to prepare the depedency package
pip install --target ./package pg
pip install --target ./package pgdb
cd package
zip -r ../deployment.zip .

[ERROR] Runtime.UserCodeSyntaxError: Syntax error in module 'lambda_function': invalid syntax (__init__.py, line 3)
Traceback (most recent call last):
  File "/var/task/pg/__init__.py" Line 3
        async,

Tried with python 3.6, 3.7 & 3.8; no luck;  googling does not seem to help much either...

**Comment by whygoyal** [comment]
Thank you for opening this issue - we are looking into it.

**Comment by samdavies1906** [comment]
Any update on this?

**Comment by Pacobart** [comment]
+1 experiencing the same issue using python 3.9. Curious, why this lambda is relying on `Python OpenGL Graphics Framework` for logging. Maybe it's a typo?

**Comment by JoeJesse** [comment]
Hello,

For this PostgreSQL rotation function, the names of the python modules that are imported by the function are not the same as the python package that needs to be installed. Unfortunately, this has been a cause of confusion. We have updated our [README](https://github.com/aws-samples/aws-secrets-manager-rotation-lambdas/blob/master/README.md) to link to our public documentation where the correct dependencies and current supported versions are outlined for each function.

For quick reference, here is the relevant link in this case: https://docs.aws.amazon.com/secretsmanager/latest/userguide/reference_available-rotation-templates.html#sar-template-postgre-singleuser

**Comment by JeffH72** [comment]
Can you publish the requirements.txt file to use and what version of python to use.

**Comment by jbct** [comment]
We are continuing to evaluate posting the requirements.txt file in the repositories, but for now the dependencies are posted to our documentation link listed above by @JoeJesse. Closing this ticket.
