### ISSUE TITLE
Oracle Issue with ORA-28221: REPLACE not specified

### ISSUE THREAD

**Issue by thegsbnut** [aws-samples/aws-secrets-manager-rotation-lambdas#79]
I try to use this script but i found the error ORA-28221: REPLACE not specified because i apply oracle user policy and it requires REPLACE syntax
(example: alter user username identified by new password  REPLACE old password )  

so how to edit the script to support  REPLACE <old password>  in line 216 : "cur.execute("ALTER USER %s IDENTIFIED BY \"%s\"" % (escaped_username, pending_password))"  

i am not the master of programing so please advise

**Comment by jbct** [comment]
Hi thegsbnut - this repository is for generic rotation lambda samples. If you are still experiencing this issue, please open a support case with AWS.
