### ISSUE TITLE
SecretsManagerMongoDBRotationSingleUser secret rotation for read & readwrite users.

### ISSUE THREAD

**Issue by devops-asService** [aws-samples/aws-secrets-manager-rotation-lambdas#81]
Hi, 
We tried rotating the secret of non-superusers using master secret. . But It tried connecting with non-superuser only in spite of enabling "use different secret" and it doesn't pick up the master arn. It appears to be the SecretsManagerMongoDBRotationSingleUser doesn't support that

**Comment by goyalya** [comment]
@devops-asService Could you please share the reproduction steps for us to guide here further.
