### ISSUE TITLE
RotationMultiUser doesn't set host and engine from masterSecret

### ISSUE THREAD

**Issue by ahammond** [aws-samples/aws-secrets-manager-rotation-lambdas#84]
I added password rotation to my database using https://github.com/time-loop/cdk-aurora/blob/main/src/aurora.ts#L284

However, it didn't
- create the user, which didn't previously exist, so I worked around it: https://github.com/time-loop/cdk-aurora/blob/main/src/aurora.provisioner.ts#L432:16
- set the newly created user's password, so... https://github.com/time-loop/cdk-aurora/blob/main/src/aurora.provisioner.ts#L454
- populate the user secret with the host and engine from the master secret, so... https://github.com/time-loop/cdk-aurora/blob/main/src/aurora.provisioner.ts#L333..L354 although really I think it should just be using masterSecret's info there.

Also, what is with the `master` stuff? BLM happened years ago. `adminSecret` or `administratorSecret` if you want to do Microsofty things. Or `mainSecret` if you want to follow GitHub's pattern. Or `primarySecret`, or `controlSecret`. It takes almost no effort at all to not be crass.

**Comment by willtong1234** [comment]
Thank you for the issue. It looks like you have resolved this problem in [this issue](https://github.com/aws/aws-cdk/issues/20704). Closing this request.

As for the inclusive language, we completely agree with the comment, but are being very careful due to backward compatibility.
