### ISSUE TITLE
functionName should not be required

### ISSUE THREAD

**Issue by cdenneen** [aws-samples/aws-secrets-manager-rotation-lambdas#87]
Currently the Application requires passing of the functionName.
All Lambda Functions allow you to not provide that value as to avoid issues with character limits exceeding the 64 character limit.

Not passing errors as:

```
Parameters: [functionName] must have values
```

**Comment by goyalya** [comment]
@cdenneen : Thanks for reporting the issue. We did some investigation and determined its working as designed. We recommend deploying samples through our supported means like Console/ CFN (https://docs.aws.amazon.com/secretsmanager/latest/userguide/rotate-secrets_turn-on-for-other.html).
