### ISSUE TITLE
Secret manager rotation expects credential key names to be constant

### ISSUE THREAD

**Issue by rbrishabh** [aws-samples/aws-secrets-manager-rotation-lambdas#89]
Hey, in the `SecretsManagerRDSMySQLRotationSingleUser/lambda_function.py` we expect the field names to be:
```
 {
        'engine': <required: must be set to 'mysql'>,
        'host': <required: instance host name>,
        'username': <required: username>,
        'password': <required: password>,
        'dbname': <optional: database name>,
        'port': <optional: if not specified, default port 3306 will be used>
    }
```

In our case, we were using key names as 'rds.engine' etc for internal purposes. 
I would expect the field names to be configurable/dynamic.
Can we look into this?
Thank you for your consideration!

**Comment by goyalya** [comment]
@rbrishabh : Thanks for the feedback. This is a sample and please feel free to modify the key names as per your needs.
