### ISSUE TITLE
randomly generated Postgres password containing colon character is not compatible with .pgpass file format

### ISSUE THREAD

**Issue by zebehringer** [aws-samples/aws-secrets-manager-rotation-lambdas#9]
We recently had a Postgres secret auto rotate with this code and the new password ended up containing a colon, which is a separator character for lib pg reading the .pgpass file

If the colon character could be added to the ExcludeCharacters attribute when randomly generating a new password then there will be no problem storing the generated secret in .pgpass

**Comment by StevenEmelander** [comment]
Thanks for posting this as well as you pull request.  We will review, test, and merge into a future release if we don't run across any issues.

**Comment by willtong1234** [comment]
This was merged in https://github.com/aws-samples/aws-secrets-manager-rotation-lambdas/commit/f2ad81c08949262b7fb8a6bc6b3833bc4f13e670. Resolving.
