### ISSUE TITLE
Generic rotation template bug in finish_secret step

### ISSUE THREAD

**Issue by ryancausey** [aws-samples/aws-secrets-manager-rotation-lambdas#92]
The [`finish_secret`](https://github.com/aws-samples/aws-secrets-manager-rotation-lambdas/blob/master/SecretsManagerRotationTemplate/lambda_function.py#L162) function has a bug in it if there is not a version found that is labeled as "AWSCURRENT".

If there is not a version found that is labeled as "AWSCURRENT", the code will set `current_version` as `None`. This will lead to `update_secret_version_stage` being called with `RemoveFromVersionId` as `None`. This results in a `ParamValidationError` being raised from the boto3 client.

**Comment by goyalya** [comment]
@ryancausey : As per the design, every secret will have a "AWSCURRENT" label.
