### ISSUE TITLE
Include requirements.txt for each folder

### ISSUE THREAD

**Issue by IyadKandalaft** [aws-samples/aws-secrets-manager-rotation-lambdas#97]
It's difficult to replicate a working version of this code without a requirements.txt file for each script or set of scripts.
Adding a requirements.txt allows developers to bring the code in-house, test it, improve it, and contribute back to this repo with ease.

**Comment by felixschwebel** [comment]
I would like to add the requirements.txt file

**Comment by jbct** [comment]
Hi lyadKandalaft - this repository is used for samples for customers to pull these in individually and modify as they see fit. The dependencies often change and we document many dependencies in the linked AWS documentation referenced in the original README. Our recommendation for deployment is for customers to use CloudFormation or [the console](https://docs.aws.amazon.com/secretsmanager/latest/userguide/rotate-secrets_turn-on-for-db.html#rotate-secrets_turn-on-for-db_step2) to automatically deploy rotation Lambdas.
