### ISSUE TITLE
SecretsManagerRDSMySQLRotationMultiUser through CloudFormation:  KeyError  'masterarn' 

### ISSUE THREAD

**Issue by v-sag** [aws-samples/aws-secrets-manager-rotation-lambdas#99]
Hi,

I am using Cloud Formation to rotate a secret with alternating users strategy using a master secret (user with admin permissions). My Cloud Formation looks like this

    ....
    SecretRotationSchedule:
      Type: AWS::SecretsManager::RotationSchedule
      DeletionPolicy: Delete
      Properties:
        SecretId: !Ref SecretId
        HostedRotationLambda:
          RotationType: MySQLMultiUser
          MasterSecretArn: !Ref AdminSecretArn
          ...
          
The Cloud Formation creation succeeds and the lambda is created, but rotation fails with `KeyError: 'masterarn'`. I looked at the source code and it seems that it expects that the secret itself has a field `masterarn`? If that is the case, then what is the purpose of CloudFormation's field `MasterSecretArn`?

I appreciate your help.

**Comment by JoeJesse** [comment]
Hi v-sag@,

Yes, it is expected that the secret you are trying to rotate will have a `masterarn` JSON key. For more info about this, please see this page in our public documentation:
[JSON structure of AWS Secrets Manager secrets](https://docs.aws.amazon.com/secretsmanager/latest/userguide/reference_secret_json_structure.html)

In regards to the purpose of that CloudFormation field, please see this section of the CloudFormation documentation for the [HostedRotationLambda resource type](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-secretsmanager-rotationschedule-hostedrotationlambda.html#cfn-secretsmanager-rotationschedule-hostedrotationlambda-mastersecretarn) as well:
> The Lambda rotation function uses this secret for the [Alternating users rotation strategy](https://docs.aws.amazon.com/secretsmanager/latest/userguide/rotating-secrets_strategies.html#rotating-secrets-two-users).

This field modifies the permissions that get attached to the rotation Lambda itself to allow it to make a [GetSecretValue](https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_GetSecretValue.html) call on that secret in addition to the one you are trying to rotate.

**Comment by v-sag** [comment]
Hi JoeJesse,

Thanks for the clarification! I appreciate it!
